#!/usr/bin/env expect -f

# netbsd/base
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

source [info script]/../../shared/lib.tcl

set spawn_id [spawn_qemu_installer [lindex $argv 1] [lindex $argv 0]]

expect "1. Boot normally"
expect "Option 1 will be chosen"
send "\r"

expect "Installation messages in English"
send "a\r"

expect "Keyboard type"
send "a\r"

expect "Install System"
send "a\r"

expect "install NetBSD on your hard disk"
expect "yes or no?"
send "b\r"
expect "Available disks"
send "a\r"
expect "This is the correct geometry"
send "a\r"
expect "install NetBSD"
expect "Use the entire disk"
send "b\r"
expect "install the NetBSD bootcode"
expect "yes or no?"
send "a\r"
expect "Choose your installation"
expect "Use existing partition sizes"
send "b\r"
expect "Partition sizes ok"
send "x\r"
expect "enter a name for your NetBSD disk"
send "\r"
expect "install NetBSD on your hard disk"
expect "yes or no?"
send "b\r"

expect "Bootblocks selection"
expect "Use serial port com0"
send "b\r"
expect "Serial port com0 at * baud"
send "f\r"
expect "e: 115200"
send "e\r"
send "x\r"

expect "Select your distribution"
send "d\r"
expect "e: Compiler tools"
send "e\r"
send "x\r"

expect "Install from"
send "a\r"

expect "Hit enter to continue"
send "\r"

expect "a: Configure network"
send "a\r"
expect "Available interfaces"
send "a\r"
expect "Network media type"
send "\r"
send "Perform autoconfiguration?"
send "a\r"
expect "Your DNS domain"
send "\r"
expect "The following are the values you entered"
expect "Are they OK?"
send "a\r"
expect "do you want it installed in /etc"
send "a\r"

expect "d: Change root password"
send "d\r"
expect "yes or no?"
send "a\r"
expect {
    "New password:" {
        send "$rootpass\r"
        exp_continue
    }
    "Retype new password:" {
        send "$rootpass\r"
    }
}
expect "g: Enable sshd"
send "g\r"
send "l\r"
send "n\r"
send "x\r"

expect "Hit enter to continue"
send "\r"

expect "x: Exit Install System"
send "x\r"

sh {
    mount /dev/sd0a /mnt
    sed -i"" 's/dhcpcd_flags="-q/dhcpcd_flags="-q4/' /mnt/etc/rc.conf
    echo 'PKG_PATH=ftp://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/8.0/All' >/mnt/etc/pkg_install.conf
    umount /mnt
    shutdown -p now
}

expect eof
