#!/bin/sh

# netbsd/download
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

set -e

target="$1"
source="$(basename "$1")"
version="$(echo "$source" | sed 's/^\(NetBSD-[^-]*\)-.*/\1/')"

curl -o "$target" "https://cdn.netbsd.org/pub/NetBSD/$version/images/$source"
