#!/usr/bin/env expect -f

# netbsd/gce
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

source [info script]/../../shared/lib.tcl

spawn_qemu_sh [lindex $argv 0] {
    echo 'mtu 1460' >> /etc/ifconfig.vioif0

    pkg_add mozilla-rootcerts >/dev/null
    mozilla-rootcerts install

    pkg_add curl

    pkg_add py27-sqlite3
    pkg_add py27-google-cloud-sdk
    ln -s /usr/pkg/bin/python2.7 /usr/pkg/bin/python
    ln -s /usr/pkg/py27-google-cloud-sdk/bin/gcloud /usr/pkg/bin
    ln -s /usr/pkg/py27-google-cloud-sdk/bin/gsutil /usr/pkg/bin
    gcloud components update --quiet

    echo '/usr/pkg/bin/curl -s -S -o /var/run/google-startup-script http://metadata.google.internal/computeMetadata/v1/instance/attributes/startup-script -H Metadata-Flavor:Google' >>/etc/rc.local
    echo 'chmod a+x /var/run/google-startup-script' >>/etc/rc.local
    echo '/var/run/google-startup-script'           >>/etc/rc.local
}
