#!/usr/bin/env expect -f

# openbsd/base
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

source [info script]/../../shared/lib.tcl

set spawn_id [spawn_qemu_installer [lindex $argv 1] [lindex $argv 0]]

expect "boot> "
send "\r"

expect "Welcome to the OpenBSD"
expect "(I)nstall"
send "I\r"

expect "keyboard layout"
send "\r"

expect "hostname"
send "openbsd\r"

expect "network interface"
send "vio0\r"
expect "IPv4"
send "dhcp\r"
expect "IPv6"
send "none\r"
expect "network interface"
send "done\r"

expect "domain name"
send "\r"

expect "Password for root"
send "$rootpass\r"
expect "Password for root"
send "$rootpass\r"

expect "sshd"
send "yes\r"

expect "X Window System"
send "no\r"

expect "default console to com0"
send "no\r"

expect "Setup a user"
send "no\r"

expect "root ssh"
send "no\r"

expect "timezone"
send "UTC\r"

# custom partitioning
#     /     95%
#     swap  5%
expect "root disk"
send "\r"
expect "(W)hole disk MBR"
send "W\r"
expect "(C)ustom layout"
send "C\r"
expect "Label editor"
expect "> "
send "a b\r"
expect "offset"
send "\r"
expect "size"
send "5%\r"
expect "FS type"
send "swap\r"
send "a a\r"
expect "offset"
send "\r"
expect "size"
send "*\r"
expect "FS type"
send "\r"
expect "mount point"
send "/\r"
expect "> "
send "p m\r"
expect "> "
send "w\r"
expect "> "
send "x\r"

expect "Location of sets"
send "\r"
expect "Pathname to the sets"
send "\r"
expect "Set name(s)"
send -- "-* +bsd* +base* +comp*\r"
expect "Set name(s)"
send "done\r"
expect "Continue without verification"
send "yes\r"
expect "Location of sets"
send "done\r"

expect "(S)hell"
send "S\r"

sh {
    sed -i"" 's@^reorder_libs$@#reorder_libs@' /mnt/etc/rc
    sed -i"" 's@^/usr/libexec/reorder_kernel@#/usr/libexec/reorder_kernel@' /mnt/etc/rc

    sed -i"" 's@^smtpd_flags=.*$@smtpd_flags=NO@' /mnt/etc/rc.conf
    sed -i"" 's@^ntpd_flags=.*$@ntpd_flags=NO@' /mnt/etc/rc.conf

    /mnt/sbin/shutdown -r now
}

expect "boot> "
send "\r"

expect "login:"
send "root\r"
expect "assword:"
send "$rootpass\r"

sh {
    echo 'set tty com0'      >/etc/boot.conf
    echo 'stty com0 115200' >>/etc/boot.conf
    echo 'boot'             >>/etc/boot.conf

    sed -i"" 's@^tty00.*$@tty00 "/usr/libexec/getty std.115200" vt100 on secure@' /etc/ttys

    shutdown -p now
}

expect eof
