#!/bin/sh

# openbsd/download
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

set -e

target="$1"
source="$(basename "$1")"
version="$(echo "$source" | sed 's/^[^0-9]*\([0-9]\)\([0-9]\).*/\1.\2/')"

curl -o "$target" -L "https://cdn.openbsd.org/pub/OpenBSD/$version/amd64/$source"
