#!/bin/sh

# freebsd/download
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

set -e

target="$1"
source="$(basename "$1")"
version="$(echo "$source" | sed 's/^FreeBSD-\([0-9]*\.[0-9]*\)-.*/\1/')"

curl -o "$target.xz" "ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/$version/$source.xz"
unxz "$target.xz"
