#!/usr/bin/env expect -f

# freebsd/go
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

source [info script]/../../shared/lib.tcl

set spawn_id [spawn_qemu_image [lindex $argv 0]]

expect "login:"
send "root\r"
expect "assword:"
send "$rootpass\r"

sh {
    pkg install -y git
    pkg install -y go

    shutdown -p now
}

expect eof
