#!/bin/sh

# imgtool
#
# Copyright 2018 Bill Zissimopoulos

# This file is part of "Poor Man's CI".
#
# It is licensed under the BSD license. The full license text can be found
# in the License.txt file at the root of this project.

set -e

qemu-system-x86_64 \
    -smp 2 \
    -device virtio-scsi \
    -blockdev driver=file,node-name=diskfile,filename="$1" \
    -blockdev driver=raw,node-name=disk,file=diskfile \
    -device scsi-hd,drive=disk \
    -net nic,model=virtio,macaddr=02:00:00:00:00:01 -net user \
    -nographic
